version: '3'  # Versão da especificação do Docker Compose

services:
  # Serviço para o aplicativo Node.js
  nodejs-app:
    image: node:14  # Imagem do Node.js
    working_dir: /app  # Diretório de trabalho dentro do contêiner
    volumes:
      - ./app:/app  # Mapeamento de volume local para o contêiner
    ports:
      - "3000:3000"  # Mapeamento de porta (host:contêiner)
    command: npm start  # Comando para iniciar o aplicativo

    #####

  mongodb:
      image: mongo:latest  # Você pode especificar a versão desejada, por exemplo, "mongo:4.4"
      container_name: mongodb
      ports:
        - "27017:27017"  # Mapeamento de porta (host:contêiner)
      volumes:
        - ./data:/data/db  # Mapeamento de volume para persistir os dados do MongoDB
      environment:
        MONGO_INITDB_ROOT_USERNAME: myuser  # Nome de usuário do administrador
        MONGO_INITDB_ROOT_PASSWORD: mypassword  # Senha do administrador
      networks:
        - mongo-network
        
networks:
  mongo-network:
    driver: bridge