version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_DATABASE: "${DB_DATABASE}"
      MONGO_USER: "${DB_USER}"
      MONGO_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "${DB_DATA_DIR}:/data"
